global_costmap:
  global_frame: map
  robot_base_frame: base_link 
  update_frequency: 0.5  
  static_map: true     
  
  rolling_window: false
  resolution: 0.05
  
  transform_tolerance: 2.0  #1.0
#map_type: costmap
#map_type: voxel
#inflation_radius: 0.1
  inflation_radius: 0.30 
  cost_scaling_factor:  15.0   # exponential rate at which the obstacle cost drops off (default:10) 
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

