<?xml version="1.0"?>
<robot name="qingzhou" xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include filename="$(find qingzhou_description)/urdf/wheel.xacro"/>
  <xacro:property name="robot_namespace" value="/qingzhou/"/>

  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Robot base dimensions -->
  <xacro:property name="base_length" value="0.5" /> 
  <xacro:property name="base_width" value="0.3" /> 
  <xacro:property name="base_height" value="0.1" /> 
  <xacro:property name="base_mass" value="5" /> 

  <!-- Wheel link dimensions -->
  <xacro:property name="wheel_radius" value="0.11" />
  <xacro:property name="wheel_thickness" value="0.08" />
  <xacro:property name="wheel_mass" value="1" />

  <!-- Steering link dimensions -->
  <xacro:property name="steer_radius" value="0.05" />
  <xacro:property name="steer_thickness" value="0.02" />
  <xacro:property name="steer_mass" value="1" />

  <!-- Axle positions -->
  <xacro:property name="axle_offset" value="0.05" />
  <xacro:property name="steer_offset" value="0.02" />
  <xacro:property name="chassis_height" value="0.045" />

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://qingzhou_description/meshes/base_link.dae" />
      </geometry>

    </visual>
  </link>

  <xacro:front_steer
    name="front"
    parent="base"
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}" 
    steer_mass="${steer_mass}" 
    base_length="${base_length}"
    base_width="${base_width}"
    axle_offset="${axle_offset}"
    steer_height="${wheel_radius+steer_offset}">
  </xacro:front_steer>

  <xacro:rear_wheel
    name="rear"
    parent="base"
    wheel_radius="${wheel_radius/4}"
    wheel_thickness="${wheel_thickness/2}"
    wheel_mass="${wheel_mass/32}">
    <origin xyz="${-base_length/2+axle_offset} 0 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel>

  <xacro:front_wheel_lr 
    name="front_right"
    parent="base"
    reflect="-1"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}" 
    wheel_mass="${wheel_mass}" 
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}" 
    steer_mass="${steer_mass}" 
    base_length="${base_length}"
    base_width="${base_width}"
    axle_offset="${axle_offset}"
    steer_height="${wheel_radius+steer_offset}">
  </xacro:front_wheel_lr>

  <xacro:front_wheel_lr
    name="front_left"
    parent="base"
    reflect="1"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}" 
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}" 
    steer_mass="${steer_mass}" 
    base_length="${base_length}"
    base_width="${base_width}"
    axle_offset="${axle_offset}"
    steer_height="${wheel_radius+steer_offset}">
  </xacro:front_wheel_lr>

  <!-- Rear wheels -->
  <xacro:rear_wheel_lr
    name="rear_right"
    parent="base"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}">
    <origin xyz="${-base_length/2+axle_offset*2} ${-base_width/2} 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel_lr>
  <xacro:rear_wheel_lr
    name="rear_left"
    parent="base"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}">
    <origin xyz="${-base_length/2+axle_offset*2} ${+base_width/2} 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel_lr>


    <link name="ydlidar_link">
        <visual>
        <!-- 0.0135-->
        <origin rpy="0 0 ${-M_PI/2}" xyz= "0 0 0.0135" />
        <geometry>
            <mesh filename="package://qingzhou_description/meshes/ydlidar_x4.dae" />
        </geometry>
        </visual>
    </link>

    <joint name="ydlidar_joint" type="fixed">
        <axis xyz="0 0 1"/>
        <origin xyz="0.145 0 ${base_height +0.015}"/>
        <parent link="base_link"/>
        <child link="ydlidar_link"/>
    </joint>

      <link name="camera_link">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.0001" length="0.0001"/>
        </geometry>
      </link>

    <joint name="camera_joint" type="fixed">
        <axis xyz="1 0 0"/>
        <origin xyz="${base_length/2+0.05} 0 ${ base_height - 0.025}"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    

    <link name="imu_link">
          <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.0001" length="0.0001"/>
        </geometry>
    </link>

    <joint name="imu_joint" type="fixed">
        <origin rpy="0 0 ${-M_PI/2}" xyz="-0.08 0 ${chassis_height + base_height/2}"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

</robot>


